apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-prometheus
  namespace: node-prometheus
  labels:
    prometheus: node-prometheus
    release: prometheus
spec:
  selector:
    matchLabels:
      app: node-prometheus
  endpoints:
  - port: http8080
    interval: 15s
    path: /metrics