apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-prometheus
  namespace: node-prometheus  
  labels:
    release: prometheus
    prometheus: node-prometheus
spec:
  selector:
    matchLabels:
      app: node-prometheus
  endpoints:
  - port: 8080
    interval: 15s
    path: /metrics